/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package daw;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author FX506
 */
public class PanelPrincipal extends javax.swing.JPanel implements ActionListener {

    private PanelBotones botonera;
    private JTextArea areaTexto;
    private String textoPantalla;

    public PanelPrincipal() {
        iniciarComponentes();
        textoPantalla = "";
    }

    private void iniciarComponentes() {
        // Creamos el panel de botones
        botonera = new PanelBotones();
        // Creamos el área de texto
        areaTexto = new JTextArea(3, 20);
        areaTexto.setEditable(false);
        areaTexto.setBackground(Color.BLACK);
        areaTexto.setForeground(Color.WHITE);
        areaTexto.setFont(new Font("Arial", Font.PLAIN, 20));

        //Establecemos layout del panel principal
        this.setLayout(new BorderLayout());
        // Colocamos la botonera y el área texto
        this.add(areaTexto, BorderLayout.NORTH);
        this.add(botonera, BorderLayout.SOUTH);

        for (JButton boton : this.botonera.getgrupoBotones()) {
            boton.addActionListener(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent ae) {
        // Se obtiene el objeto que desencadena el evento
        Object o = ae.getSource();
        // Si es un botón
        if (o instanceof JButton) {

            String textoBoton = ((JButton) o).getText();

            if (textoPantalla.contains("=")) {
                textoPantalla = "";
            }

            switch (textoBoton) {
                case "+":
                    textoPantalla += " + ";
                    break;
                case "-":
                    textoPantalla += " - ";
                    break;
                case "*":
                    textoPantalla += " * ";
                    break;
                case "/":
                    textoPantalla += " / ";
                    break;
                case "=":
                try {
                    textoPantalla += " = " + calcularResultado(textoPantalla);
                } catch (Exception e) {
                    textoPantalla = "Syntax Error";
                }
                break;
                case "C":
                    textoPantalla = "";
                    break;
                default:
                    textoPantalla += textoBoton;
                    break;
            }
            areaTexto.setText(textoPantalla);
        }
    }

    private double calcularResultado(String textoPantalla) throws Exception {
        String[] numeros = textoPantalla.split(" ");
        if (numeros.length != 3) {
            throw new Exception("Syntax Error");
        }
        double num1 = Double.parseDouble(numeros[0]);
        double num2 = Double.parseDouble(numeros[2]);
        switch (numeros[1]) {
            case "+":
                return num1 + num2;
            case "-":
                return num1 - num2;
            case "*":
                return num1 * num2;
            case "/":
                if (num2 == 0) {
                    throw new Exception("Syntax Error");
                }
                return num1 / num2;
            default:
                throw new Exception("Syntax Error");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
