/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package daw;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author FX506
 */
public class PanelPrincipal extends javax.swing.JPanel implements ActionListener {

    private PanelBotones botonera;
    private JTextArea areaTexto;
    private int tipoOperacion;
    private String textoPantalla;

    public PanelPrincipal() {
        iniciarComponentes();
        textoPantalla = "";
        tipoOperacion = -1;
    }

    private void iniciarComponentes() {
        // Creamos el panel de botones
        botonera = new PanelBotones();
        // Creamos el área de texto
        areaTexto = new JTextArea(6, 30);
        areaTexto.setEditable(false);
        areaTexto.setBackground(Color.white);

        //Establecemos layout del panel principal
        this.setLayout(new BorderLayout());
        // Colocamos la botonera y el área texto
        this.add(areaTexto, BorderLayout.NORTH);
        this.add(botonera, BorderLayout.SOUTH);

        for (JButton boton : this.botonera.getgrupoBotones()) {
            boton.addActionListener(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent ae) {
        // Se obtiene el objeto que desencadena el evento
        Object o = ae.getSource();
        // Si es un botón
        if (o instanceof JButton) {

            textoPantalla += ((JButton) o).getText();
            areaTexto.setText(textoPantalla);

            if (((JButton) o).getText().equals("=")) {
                try {
                    if (((JButton) o).getText().equals("+")) {
                        String[] numeros = textoPantalla.split("\\+=");
                        int resultado = Integer.parseInt(numeros[0]) + Integer.parseInt(numeros[1]);
                        textoPantalla += resultado;
                    }
                    if (jLabel1.getText().contains("-")) {
                        String[] numeros = textoPantalla.getText().split("-");
                        int resultado = Integer.parseInt(numeros[0]) - Integer.parseInt(numeros[1]);
                        jLabel1.setText(String.valueOf(resultado));
                    }
                    if (jLabel1.getText().contains("/")) {
                        String[] numeros = jLabel1.getText().split("/");
                        int resultado = Integer.parseInt(numeros[0]) / Integer.parseInt(numeros[1]);
                        jLabel1.setText(String.valueOf(resultado));
                    }
                    if (jLabel1.getText().contains("x")) {
                        String[] numeros = jLabel1.getText().split("x");
                        int resultado = Integer.parseInt(numeros[0]) * Integer.parseInt(numeros[1]);
                        jLabel1.setText(String.valueOf(resultado));
                    }
                } catch (NumberFormatException nfe) {
                    jLabel1.setText("Syntax Error");
                }
            }

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
